<?php

declare(strict_types=1);

const ROLE_ADMIN = 'ADMIN';
const ROLE_CASHIER = 'CASHIER';

const SESSION_TIMEOUT_DEFAULT = 28800; // 8 hours

const PAYMENT_METHOD_CASH = 'CASH';
const PAYMENT_METHOD_MOBILE_MONEY = 'MOBILE_MONEY';
const PAYMENT_METHOD_CARD = 'CARD';

const SALE_STATUS_COMPLETED = 'COMPLETED';
const SALE_STATUS_VOIDED = 'VOIDED';

const SHIFT_STATUS_OPEN = 'OPEN';
const SHIFT_STATUS_CLOSED = 'CLOSED';

const MOVEMENT_STOCK_IN = 'STOCK_IN';
const MOVEMENT_STOCK_OUT = 'STOCK_OUT';
const MOVEMENT_ADJUSTMENT = 'ADJUSTMENT';

const MAX_DISCOUNT_PERCENT = 20;
